database:
  type: 'NEO4J'
  uri: 'bolt://debianvm:7687'
default_parameters:
  goals:
    type: area
    area:
      rails: all
      railArea: all
      railSide: all
      crossbeamSide: all
  situations:
    robot_situation:
      effector:
        definition:
          uid: 'effector'
          description: 'effector state meta object'
        state: 'no_effector'
        priority: 0
        relation: 'eq'
      station:
        definition:
          uid: 'station'
          description: 'station state meta object'
        state: 'home_station'
        relation: 'eq'
        priority: 0
      tcp_approach:
        definition: 
          uid: 'tcp_approach'
          description: 'tcp approach state meta object'
        state: 'move_station_position'
        relation: 'eq'
        priority: 0
      tcp_work:
        definition: 
          uid: 'tcp_work'
          description: 'tcp work state meta object'
        state: 'out_work'
        priority: 0
        relation: 'eq'
    work_situation:
      kff_yn1292:
        definition:
          description: state meta object for reference flange rear at y-1292
          uid: kff_y-1292
        priority: 0
        relation: eq
        state: no_probed
      kff_yn254:
        definition:
          description: state meta object for reference flange rear at y-254
          uid: kff_y-254
        priority: 0
        relation: eq
        state: no_probed
      kff_yn763:
        definition:
          description: state meta object for reference flange rear at y-763
          uid: kff_y-763
        priority: 0
        relation: eq
        state: no_probed
      kff_yp1292:
        definition:
          description: state meta object for reference flange rear at y+1292
          uid: kff_y+1292
        priority: 0
        relation: eq
        state: no_probed
      kff_yp254:
        definition:
          description: state meta object for reference flange rear at y+254
          uid: kff_y+254
        priority: 0
        relation: eq
        state: no_probed
      kff_yp763:
        definition:
          description: state meta object for reference flange rear at y+763
          uid: kff_y+763
        priority: 0
        relation: eq
        state: no_probed
      kfr_yn1292:
        definition:
          description: state meta object for reference flange rear at y-1292
          uid: kfr_y-1292
        priority: 0
        relation: eq
        state: no_probed
      kfr_yn254:
        definition:
          description: state meta object for reference flange rear at y-254
          uid: kfr_y-254
        priority: 0
        relation: eq
        state: no_probed
      kfr_yn763:
        definition:
          description: state meta object for reference flange rear at y-763
          uid: kfr_y-763
        priority: 0
        relation: eq
        state: no_probed
      kfr_yp1292:
        definition:
          description: state meta object for reference flange rear at y+1292
          uid: kfr_y+1292
        priority: 0
        relation: eq
        state: no_probed
      kfr_yp254:
        definition:
          description: state meta object for reference flange rear at y+254
          uid: kfr_y+254
        priority: 0
        relation: eq
        state: no_probed
      kfr_yp763:
        definition:
          description: state meta object for reference flange rear at y+763
          uid: kfr_y+763
        priority: 0
        relation: eq
        state: no_probed